# Generated by Django 2.0.5 on 2019-05-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_rating', '0002_auto_20190501_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='chair',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
