# Generated by Django 2.0.5 on 2019-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_rating', '0003_auto_20190501_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
