# Generated by Django 2.0.5 on 2019-05-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_rating', '0004_teacher_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chair',
            options={'ordering': ['title'], 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['chair'], 'verbose_name': 'Прподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
