# Generated by Django 2.0.5 on 2019-05-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_rating', '0009_auto_20190511_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(default='deafault.png', upload_to=''),
        ),
    ]
